### ISSUE TITLE
TEXTING & VC POINT REWARD [FEATURE]

### ISSUE THREAD

**Issue by Psento** [pointsbot/bugs#10]
### TEXTING & VC POINT REWARD [FEATURE]

Texting and voice chatting can reward the user with a point reward(in the given channel of choice),
 texting and voice chatting would have 3 variable integer-ranges,
 default at first(Can modify.), 

1. Amount of texts to send (18-32)
2. Time in vc (2h-5h or7200s-18000s)
3. Point Reward amount.

The point reward is a token of sorts, 
 you must claim it to receive it,
 The message sent to the user should inform them of what has happened,
 follow a similar format to your other rewards(with variables we can change.),
 two ways to go about it that I can muster.

### FIRST METHOD DISABLED STACKING
 - By default doesn't stack the amount of rewards you have gained,
 needs to claim the reward before you can receive your next.

______________

**@User**
**REWARD**
You now have gained a reward!
_**/Reward** to claim!_

_dismiss this message_

**@User**
**REWARD CLAIMED**
**(AMOUNT OF POINTS GAINED)**

_dismiss this message_

### SECOND METHOD ENABLED STACKING
 - When the stacking of rewards is enabled, show the person the amount of point claims the user has when receiving the point claim, using a message sent by the bot.

______________

**@User**
**REWARD**
You now have gained a reward!
**(AMOUNT OF REWARDS YOU HAVE)**
_**/Reward** to claim!_

_dismiss this message_

**@User**
**REWARD CLAIMED**
**(AMOUNT OF POINTS GAINED)** **(AMOUNT OF REWARDS YOU HAVE)**

_dismiss this message_

**Comment by GriffinSego** [comment]
I appreciate the amount of effort you have put into this featreq but it would be very challenging to add this feature because it falls outside the scope of our current codebase and permissions access.
