### ISSUE TITLE
[FEATURE]: Log Channel

### ISSUE THREAD

**Issue by LOL0JP** [pointsbot/bugs#17]
### Discord Username

sign#0001

### What's your idea?

add a "log channel" to see who gave someone points when someone might delete the bot message. It will really help out many servers, i am sure. 
![image](https://github.com/pointsbot/bugs/assets/134896877/1c804d98-c265-4161-91fa-cf03156d8af2) something like this.

**Comment by A-da-m** [comment]
This feature has been implemented, you can set a webhook under Settings -> Customization in the dashboard, it will log all commands run like points management, items bought etc.
