### ISSUE TITLE
[FEATURE]: 

### ISSUE THREAD

**Issue by a1ma1moco** [pointsbot/bugs#18]
### Discord Username

@a1ma1moco

### What's your idea?

Hello. Thank you for the other day.

I would like to have the opportunity to earn points for voice chat as well.
For example, if you connect to voice chat for 1 minute, you will earn 1 point.
I would appreciate it if you could consider it.

**Comment by GriffinSego** [comment]
This is outside the scope of the current system, and permissions level, making this impractical to target. It would require a disproportionate amount of development time to accomplish this, when we could be implementing other features that we are better equipped to implement faster.
