### ISSUE TITLE
[BUG] Bot: Role Failing to Add

### ISSUE THREAD

**Issue by heyitisdestiny** [pointsbot/bugs#2]
**Describe the bug**
When buying something with a role attached, the bot is not adding the user. I think this may be due to the bot mixing up name with ID. (See bellow).

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a item with a role.
2. Buy the role.

**Expected behaviour**
The bot will give the role.

**Screenshots**
![image](https://user-images.githubusercontent.com/68116419/185995980-45c877a6-e7d1-435b-873b-1c3bb450057f.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**

**Comment by A-da-m** [comment]
a fix has been deployed for this bug please reproduce. reopen ticket if still present

(the dashboard does not show the role on the item card, it will be added later)
