### ISSUE TITLE
[FEATURE]: Movable shop items

### ISSUE THREAD

**Issue by meripurrsa** [pointsbot/bugs#21]
### Discord Username

meripurrsa

### What's your idea?

I think making the items in the shop movable/adjustable would be awesome! Cause I like items grouped up so when I make an item that doesn't fit with the latest items added, it drives me mad. And I don't want to keep deleting the items just to move the newly added item to be grouped up

**Comment by GriffinSego** [comment]
@maripurrsa
Hi, could you clarify a bit more about what specific arrangement functionality you are requesting? Simple linear rearrangement should be easy enough while many other potential moves or adjustments could be impractical to develop

**Comment by meripurrsa** [comment]
I mean like, if there's multiple people buying different things for
different purposes. Like I want to use it for roleplay but the roleplay
will allow multiple characters so I wanna be able to allow people buy
multiple things but for different characters

**Comment by A-da-m** [comment]
@meripurrsa this feature was added in the latest update
