### ISSUE TITLE
When adding a role through /create, role does not show up in /shop.

### ISSUE THREAD

**Issue by TheGamingWubba** [pointsbot/bugs#4]
**Issue:** When running /create with all the correct parameters, role does not show up in /shop. If attempting to run command again, it says role already exists. Particularly a problem considering issue #2, as currently there is no way to add a role.

**Expected behavior:** Bot adds role to shop, which is given on purpose.

**Actual behavior:** _Does not show up whatsoever_.

Currently have to manually give members the role & take points, so they have to DM me if they'd like it.

**Comment by A-da-m** [comment]
this has been fixed, if you still run into this please reopen the issue!
