### ISSUE TITLE
[BUG] Premium Points only shows up for admin, not for users of the server

### ISSUE THREAD

**Issue by mortaine** [pointsbot/bugs#8]
I am a Premium Points subscriber (Patreon and am in the discord with the correct role).

I added Points to a discord server that I own and enabled a premium feature (rename the currency).

One of my users used the bot, but the feature displays as "Points," is blue, and refers to the currency as "points" instead of "coins."

Screen shot attached.

![Discord_2022-10-21_05-10-46](https://user-images.githubusercontent.com/25754922/197193147-f692fb74-7c93-49d1-9732-9ecc4a471ddf.png)

**Comment by A-da-m** [comment]
Currently Premium Basic only applies to the person who bought it. Premium Plus unlocks it for the rest of the server.

**Comment by GriffinSego** [comment]
Feature works as intended
